### ISSUE TITLE
نسخه npm, composer 

### ISSUE THREAD

**Issue by sajaddp** [Hesammousavi/bootstrap-v4-rtl#4]
<div dir="rtl">
سلام

آقاجان لطفا نسخه Npm و composer منتشر کنید.

همین طور لطفا علاوه بر معرفی درمقالات سایت خودتون یک فراخوان هم در کانال بزنید که افراد در سایت های خودشون معرفی کنند.

هرچند که این نسخه هم هنوز جای کار داره
ولی به شخصه معتقدم از برخی از پکیج هایی که کل هسته رو دستکاری کردند مناسب تر هست.

</div>

**Comment by Hesammousavi** [comment]
<div dir="rtl">
با سلام

تشکر انجام شد 👍
</div>
