### ISSUE TITLE
چک باکس ها درست نمایش داده نمی شود

### ISSUE THREAD

**Issue by Hamipia** [Hesammousavi/bootstrap-v4-rtl#5]
سلام
در قسمت مربوط به فرم، چک باکسها درست نمایش داده نمی شوند. قسمت باکس و قسمت برچسب با هم تداخل دارند و جهت رفع آن احتیاج به 
اضافه کردن تغییراتی در پدینگ و مارجینگ هست تا درست نمایش داده بشن

.form-check {
  padding-right: 1.25rem !important;
}

.form-check-input {
  margin-right: -1.25rem !important;
}

با تشکر فراوان از شما

**Comment by Hesammousavi** [comment]
<div align="right">
تشکر از شما باگ برطرف شد
</div>
